server:
  port: 9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/

spring:
  application:
    name: socket
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url:
    username:
    password:
    # 连接池配置
    hikari:
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-timeout: 30000
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 600000
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL
      max-lifetime: 1800000
      # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximum-pool-size: 2
      minimum-idle: 1


#----------------------Swagger2配置-------------------
swagger2:
  open: true
  testToken: Bearer Get after landing
  basePackage: ${spring.basePackage}
  name: L前端api接口
  url:
  email:
  title: springboot利用swagger构建api文档
  description: springboot利用swagger构建api文档







