server:
  port: 9091
spring:
  basePackage: com.example.zuul
  application:
    name: zuul

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9090/eureka/

#----------------------Swagger2配置-------------------
swagger2:
  open: true
  testToken: Bearer Get after landing
  basePackage: ${spring.basePackage}
  name: L前端api接口
  url:
  email:
  title: springboot利用swagger构建api文档
  description: springboot利用swagger构建api文档


zuul:
  routes:
    socket:
      path: /socket/**
      serviceId: socket




