server:
  port: 9091
spring:
  application:
    name: zuul

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9090/eureka/


zuul:
  routes:
    socket:
      path: /socket/**
      serviceId: socket



